version: '3.9'
services:
    # Run watchtower to automatically update containers when a new image is pushed
    watchtower:
      image: containrrr/watchtower:1.4.0
      restart: unless-stopped
      environment:
        WATCHTOWER_POLL_INTERVAL: 3600
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    # Run the caddy server as a reverse proxy   
    reverse_proxy: 
      image: caddy:2.6.2-alpine
      restart: unless-stopped
      deploy:
        labels:
          com.centurylinklabs.watchtower.enable: "false"
      ports:
          - "80:80"
          - "443:443"
      volumes:            
        - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
    # Run the front end for icehotburn.dev
    icehotburn.dev:
      image: "ghcr.io/icehotburn/icehotburn-dev:main"
      restart: unless-stopped
volumes:
  caddy_data:
  caddy_config: 


