name: Icehotburn.dev Healthcheck

on:
  schedule:
    - cron: "*/5 * * * *" # minimum time period for scheduled runs is 5 minutes

permissions: {}

jobs:
  # JOB to run healthcheck
  healthcheck:
    steps:
      - name: Check that icehotburn.dev is up
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://icehotburn.dev|http://icehotburn.dev
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
