name: Icehotburn.dev CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # JOB to run change detection
  change_detection:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changes in icehotburn.dev/*
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'icehotburn.dev/**'

  # JOB to build and test the code in icehotburn.dev
  build_and_test_code:
    needs: change_detection
    if: ${{ github.ref != 'refs/heads/main'  && needs.change_detection.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: icehotburn.dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: "npm"
          cache-dependency-path: icehotburn.dev/package-lock.json
      - name: Build and test with Node.js 18.12.0
        run: |
          npm ci
          npm run build
          npm run test:unit
          npm run test:e2e:ci

  # JOB to build and publish a docker image for the code in incehotburn.dev
  build_and_publish_image:
    needs: change_detection
    if: ${{ github.ref == 'refs/heads/main' && needs.change_detection.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: icehotburn.dev
    env:
      REGISTRY: ghcr.io
      OWNER: icehotburn
      IMAGE_NAME: icehotburn-dev
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./icehotburn.dev
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
